#include "FileEpisode.h"




QString FileEpisode::getSimpleName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000883 begin
{
    return "todo: " + getName();
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000883 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool FileEpisode::moveFile(int idRessource)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000902 begin
{
    return false;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000902 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
