#include "FileMusic.h"

FileMusic::FileMusic()
{
    _ressourceMusics = QList<RessourceMusic *>();

    _ressourceMusics.insert(0, new RessourceMusic);
    _ressourceMusics.insert(0, new RessourceMusic);
}



QString FileMusic::getSimpleName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000881 begin
{
    return "todo: (" + QString::number(_ressourceMusics.length()) + ") " + getName();
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000881 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool FileMusic::moveFile(int idRessource)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000905 begin
{
    return false;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000905 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
