#include "FileFilm.h"

FileFilm::FileFilm()
{
    _ressourceFilms = QList<RessourceFilm *>();

    _ressourceFilms.insert(0, new RessourceFilm);
    _ressourceFilms.insert(0, new RessourceFilm);
}

QString FileFilm::getSimpleName()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000885 begin
{
    return "todo: (" + QString::number(_ressourceFilms.length()) + ") " + getName();
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000885 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool FileFilm::moveFile(int idRessource)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008FF begin
{
    return false;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008FF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
