#include "Format.h"

Format::Format()
{

}


QString Format::getExemple()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008AE begin
{
    return QString("");
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008AE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
