#include "RessourceEpisode.h"




QString RessourceEpisode::getTvShow()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008E2 begin
{
    return _tvShow;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008E2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString RessourceEpisode::getSeason()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008E7 begin
{
    return _season;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008E7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int RessourceEpisode::getEpisodeNum()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008E9 begin
{
    return _episodeNum;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008E9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString RessourceEpisode::getTitle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008EB begin
{
    return _title;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008EB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
