#include "RessourceMusic.h"



QString RessourceMusic::getArtist()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008F8 begin
{
    return _artist;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008F8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString RessourceMusic::getAlbulm()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008FB begin
{
    return _albulm;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008FB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString RessourceMusic::getTitle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008FD begin
{
    return _title;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:00000000000008FD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
