#include "RessourceFilm.h"




QString RessourceFilm::getTitle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000896 begin
{
    return _title;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000896 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int RessourceFilm::getYear()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000898 begin
{
    return _year;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000898 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString RessourceFilm::getImdbID()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:000000000000089A begin
{
    return _imdbID;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:000000000000089A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QString RessourceFilm::getPhotoURL()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:000000000000089C begin
{
    return _photoURL;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:000000000000089C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
