#include "TypeMedia.h"

TypeMedia::TypeMedia()
{
    _formats = QList<Format *>();
}


QString TypeMedia::getFormat()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000908 begin
{
    return QString("");
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000908 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

QList<Format *> TypeMedia::getFormats()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000910 begin
{
    return _formats;
}
// section -64--88-0-19-eb431c4:1417ae9b2f7:-8000:0000000000000910 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
